app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin