# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
    admin.site:
        class: AppBundle\Admin\SiteAdmin
        arguments: [~, AppBundle\Entity\Site, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Site }
    admin.settings:
        class: AppBundle\Admin\SettingsAdmin
        arguments: [~, AppBundle\Entity\Settings, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Settings }